In [1]:
# Activity 1.02 - Forest Fire Size and Temperature Analysis
## Student ID: mc64920

In [2]:
import pandas as pd

In [3]:
forestfires = pd.read_csv('forestfires.csv')

In [4]:
forestfires.head(2)

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0

In [5]:
forestfires.shape

(517, 13)

In [6]:
forestfires.columns

Index(['X', 'Y', 'month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH',
       'wind', 'rain', 'area'],
      dtype='str')

In [7]:
fires = forestfires[forestfires['area'] > 0]
fires.head()

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
138  9  9   jul  tue  85.8   48.3  313.4   3.9  18.0  42   2.7   0.0  0.36
139  1  4   sep  tue  91.0  129.5  692.6   7.0  21.7  38   2.2   0.0  0.43
140  2  5   sep  mon  90.9  126.5  686.5   7.0  21.9  39   1.8   0.0  0.47
141  1  2   aug  wed  95.5   99.9  513.3  13.2  23.3  31   4.5   0.0  0.55
142  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9   0.0  0.61

In [8]:
fires['area'].mean()

np.float64(24.600185185185182)

In [9]:
fires['area'].min()

np.float64(0.09)

In [10]:
fires['area'].max()

np.float64(1090.84)

In [11]:
fires['area'].std()

np.float64(86.50163460412126)

In [12]:
fires_sorted = fires.sort_values(by='area')
fires_sorted.tail(20)

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain     area
469  6  3   apr  sun  91.0   14.6   25.6  12.3  13.7  33   9.4   0.0    61.13
228  4  6   sep  sun  93.5  149.3  728.6   8.1  28.3  26   3.1   0.0    64.10
473  9  4   jun  sat  90.5   61.1  252.6   9.4  24.5  50   3.1   0.0    70.32
392  1  3   sep  sun  91.0  276.3  825.1   7.1  21.9  43   4.0   0.0    70.76
229  8  6   aug  sat  92.2   81.8  480.8  11.9  16.4  43   4.0   0.0    71.30
457  1  4   aug  wed  91.7  191.4  635.9   7.8  19.9  50   4.0   0.0    82.75
293  7  6   jul  tue  93.1  180.4  430.8  11.0  26.9  28   5.4   0.0    86.45
230  4  4   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0    88.49
231  1  5   sep  sun  93.5  149.3  728.6   8.1  27.8  27   3.1   0.0    95.18
232  6  4   sep  tue  91.0  129.5  692.6   7.0  18.7  43   2.7   0.0   103.39
233  9  4   sep  tue  84.4   73.4  671.9   3.2  24.3  36   3.1   0.0   105.66
234  4  5   sep  sat  92.5  121.1  674.4   8.6  17.7  25   3.1   0.0   154.88
377  2  2   aug  sat  93.7  231.1  715.1   8.4  21.9  42   2.2   0.0   174.63
420  8  8   aug  wed  91.7  191.4  635.9   7.8  26.2  36   4.5   0.0   185.76
235  8  6   aug  sun  91.4  142.4  601.4  10.6  19.6  41   5.8   0.0   196.48
236  2  2   sep  sat  92.5  121.1  674.4   8.6  18.2  46   1.8   0.0   200.94
237  1  2   sep  tue  91.0  129.5  692.6   7.0  18.8  40   2.2   0.0   212.88
479  7  4   jul  mon  89.2  103.9  431.6   6.4  22.6  57   4.9   0.0   278.53
415  8  6   aug  thu  94.8  222.4  698.6  13.9  27.5  27   4.9   0.0   746.28
238  6  5   sep  sat  92.5  121.1  674.4   8.6  25.1  27   4.0   0.0  1090.84

In [13]:
fires['area'].median()

np.float64(6.37)

In [14]:
fires['area'].mean()

np.float64(24.600185185185182)

In [15]:
forestfires['month'].unique()

<ArrowStringArray>
['mar', 'oct', 'aug', 'sep', 'apr', 'jun', 'jul', 'feb', 'jan', 'dec', 'may',
 'nov']
Length: 12, dtype: str

In [16]:
forestfires[forestfires['month'] == 'mar'].shape

(54, 13)

In [17]:
months = forestfires['month'].unique()

for month in months:
    data = forestfires[forestfires['month'] == month]
    num_fires = data.shape[0]
    mean_temp = data['temp'].mean()
    print(f"Month: {month}, Number of fires: {num_fires}, Mean temperature: {mean_temp}")

Month: mar, Number of fires: 54, Mean temperature: 13.083333333333334
Month: oct, Number of fires: 15, Mean temperature: 17.093333333333337
Month: aug, Number of fires: 184, Mean temperature: 21.631521739130434
Month: sep, Number of fires: 172, Mean temperature: 19.61220930232558
Month: apr, Number of fires: 9, Mean temperature: 12.044444444444444
Month: jun, Number of fires: 17, Mean temperature: 20.49411764705882
Month: jul, Number of fires: 32, Mean temperature: 22.109375
Month: feb, Number of fires: 20, Mean temperature: 9.634999999999998
Month: jan, Number of fires: 2, Mean temperature: 5.25
Month: dec, Number of fires: 9, Mean temperature: 4.522222222222222
Month: may, Number of fires: 2, Mean temperature: 14.65
Month: nov, Number of fires: 1, Mean temperature: 11.8